# Name of the executable
EXE=minimac
########################
# The Files:
TOOLBASE = HaplotypeClipper HaplotypeSet ImputationStatistics MarkovModel MarkovParameters
SRCONLY = Main.cpp
HDRONLY = 

########################
# Include the base Makefile
PARENT_MAKE = Makefile.src
include ../Makefile.inc
